# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# https://github.com/Azure/actions-workflow-samples/tree/master/Kubernetes
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace:
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).
name: build
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: k8scc01covidacr
  CLUSTER_NAME: k8s-cancentral-01-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    # Container build and push to a Azure Container registry (ACR)
    - run: |
        # Remote Desktop Base
        docker build -f base/Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${{ github.sha }} base
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${{ github.sha }}
        docker tag ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${{ github.sha }} ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${GITHUB_REF#refs/*/}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${GITHUB_REF#refs/*/}
        docker system prune -f -a

    # Scan image for vulnerabilities
    - uses: Azure/container-scan@v0
      env:
        TRIVY_TIMEOUT: 10m0s #trivy default is 2
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-base:${{ github.sha }}
        severity-threshold: CRITICAL
        run-quality-checks: false

    # Container build and push to a Azure Container registry (ACR)
    - run: |
        # Remote Desktop R
        docker build -f r/Dockerfile --build-arg SHA=${{ github.sha }} -t ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${{ github.sha }} r
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${{ github.sha }}
        docker tag ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${{ github.sha }} ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${GITHUB_REF#refs/*/}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${GITHUB_REF#refs/*/}
        docker system prune -f -a

    # Scan image for vulnerabilities
    - uses: Azure/container-scan@v0
      env:
        TRIVY_TIMEOUT: 10m0s #Trivy default is 2
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-r:${{ github.sha }}
        severity-threshold: CRITICAL
        run-quality-checks: false

    # Container build and push to a Azure Container registry (ACR)
    - run: |
        # Remote Desktop Geomatics
        docker build -f geomatics/Dockerfile --build-arg SHA=${{ github.sha }} -t ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${{ github.sha }} geomatics
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${{ github.sha }}
        docker tag ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${{ github.sha }} ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${GITHUB_REF#refs/*/}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${GITHUB_REF#refs/*/}
        docker system prune -f -a

    # Scan image for vulnerabilities
    - uses: Azure/container-scan@v0
      env:
        TRIVY_TIMEOUT: 10m0s #Trivy default is 2
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/remote-desktop-geomatics:${{ github.sha }}
        severity-threshold: CRITICAL
        run-quality-checks: false
    
